-- Portfolio V1 database foundation.
-- Apply only to the approved development project after inspecting its catalog.
-- This migration deliberately uses CREATE without IF NOT EXISTS so name conflicts fail.

BEGIN;

CREATE TABLE public.profiles (
  profile_id smallint PRIMARY KEY DEFAULT 1,
  display_name text NOT NULL,
  headline text NOT NULL,
  short_intro text NOT NULL,
  about_text text NOT NULL,
  CONSTRAINT profiles_singleton CHECK (profile_id = 1),
  CONSTRAINT profiles_display_name_not_blank CHECK (btrim(display_name) <> ''),
  CONSTRAINT profiles_headline_not_blank CHECK (btrim(headline) <> ''),
  CONSTRAINT profiles_short_intro_not_blank CHECK (btrim(short_intro) <> ''),
  CONSTRAINT profiles_about_text_not_blank CHECK (btrim(about_text) <> '')
);

CREATE TABLE public.profile_links (
  link_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id smallint NOT NULL,
  link_type text NOT NULL,
  label text NOT NULL,
  href text NOT NULL,
  display_order integer NOT NULL,
  CONSTRAINT profile_links_profile_id_fkey
    FOREIGN KEY (profile_id) REFERENCES public.profiles (profile_id)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT profile_links_profile_href_key UNIQUE (profile_id, href),
  CONSTRAINT profile_links_type_check
    CHECK (link_type IN ('email', 'github', 'linkedin', 'other')),
  CONSTRAINT profile_links_label_not_blank CHECK (btrim(label) <> ''),
  CONSTRAINT profile_links_href_not_blank CHECK (btrim(href) <> ''),
  CONSTRAINT profile_links_display_order_check CHECK (display_order >= 0)
);

CREATE TABLE public.projects (
  project_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  summary text NOT NULL,
  problem_text text,
  solution_text text,
  contribution_text text,
  status text NOT NULL,
  is_published boolean NOT NULL DEFAULT false,
  is_featured boolean NOT NULL DEFAULT false,
  display_order integer NOT NULL,
  cover_asset_path text,
  cover_alt_text text,
  CONSTRAINT projects_slug_format_check
    CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  CONSTRAINT projects_title_not_blank CHECK (btrim(title) <> ''),
  CONSTRAINT projects_summary_not_blank CHECK (btrim(summary) <> ''),
  CONSTRAINT projects_status_check CHECK (status IN ('completed', 'in_progress')),
  CONSTRAINT projects_display_order_check CHECK (display_order >= 0),
  CONSTRAINT projects_cover_pair_check CHECK (
    (cover_asset_path IS NULL AND cover_alt_text IS NULL)
    OR (
      cover_asset_path IS NOT NULL
      AND btrim(cover_asset_path) <> ''
      AND cover_alt_text IS NOT NULL
      AND btrim(cover_alt_text) <> ''
    )
  )
);

CREATE TABLE public.technology_categories (
  category_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  display_order integer NOT NULL,
  CONSTRAINT technology_categories_slug_not_blank CHECK (btrim(slug) <> ''),
  CONSTRAINT technology_categories_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT technology_categories_display_order_check CHECK (display_order >= 0)
);

CREATE TABLE public.technologies (
  technology_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id bigint NOT NULL,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  display_order integer NOT NULL,
  show_in_stack boolean NOT NULL DEFAULT false,
  CONSTRAINT technologies_category_id_fkey
    FOREIGN KEY (category_id) REFERENCES public.technology_categories (category_id)
    ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT technologies_slug_not_blank CHECK (btrim(slug) <> ''),
  CONSTRAINT technologies_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT technologies_display_order_check CHECK (display_order >= 0)
);

CREATE TABLE public.project_technologies (
  project_id bigint NOT NULL,
  technology_id bigint NOT NULL,
  CONSTRAINT project_technologies_pkey PRIMARY KEY (project_id, technology_id),
  CONSTRAINT project_technologies_project_id_fkey
    FOREIGN KEY (project_id) REFERENCES public.projects (project_id)
    ON UPDATE RESTRICT ON DELETE CASCADE,
  CONSTRAINT project_technologies_technology_id_fkey
    FOREIGN KEY (technology_id) REFERENCES public.technologies (technology_id)
    ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX project_technologies_technology_project_idx
  ON public.project_technologies (technology_id, project_id);

CREATE TABLE public.project_links (
  link_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL,
  link_type text NOT NULL,
  label text NOT NULL,
  url text NOT NULL,
  display_order integer NOT NULL,
  CONSTRAINT project_links_project_id_fkey
    FOREIGN KEY (project_id) REFERENCES public.projects (project_id)
    ON UPDATE RESTRICT ON DELETE CASCADE,
  CONSTRAINT project_links_project_url_key UNIQUE (project_id, url),
  CONSTRAINT project_links_type_check
    CHECK (link_type IN ('repository', 'live', 'case_study', 'other')),
  CONSTRAINT project_links_label_not_blank CHECK (btrim(label) <> ''),
  CONSTRAINT project_links_url_not_blank CHECK (btrim(url) <> ''),
  CONSTRAINT project_links_url_https_check
    CHECK (url ~ '^https://[^[:space:]]+$'),
  CONSTRAINT project_links_display_order_check CHECK (display_order >= 0)
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.technology_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.technologies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_technologies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_links ENABLE ROW LEVEL SECURITY;

-- Supabase may provide default privileges on new public-schema tables.
-- Remove browser-role privileges first, then grant SELECT to anon only.
REVOKE ALL ON TABLE
  public.profiles,
  public.profile_links,
  public.projects,
  public.technology_categories,
  public.technologies,
  public.project_technologies,
  public.project_links
FROM PUBLIC, anon, authenticated;

GRANT SELECT ON TABLE
  public.profiles,
  public.profile_links,
  public.projects,
  public.technology_categories,
  public.technologies,
  public.project_technologies,
  public.project_links
TO anon;

CREATE POLICY profiles_public_select
  ON public.profiles FOR SELECT TO anon
  USING (profile_id = 1);

CREATE POLICY profile_links_public_select
  ON public.profile_links FOR SELECT TO anon
  USING (profile_id = 1);

CREATE POLICY projects_public_select
  ON public.projects FOR SELECT TO anon
  USING (is_published = true);

CREATE POLICY technology_categories_public_select
  ON public.technology_categories FOR SELECT TO anon
  USING (true);

CREATE POLICY technologies_public_select
  ON public.technologies FOR SELECT TO anon
  USING (true);

CREATE POLICY project_technologies_public_select
  ON public.project_technologies FOR SELECT TO anon
  USING (
    EXISTS (
      SELECT 1 FROM public.projects AS p
      WHERE p.project_id = project_technologies.project_id
        AND p.is_published = true
    )
  );

CREATE POLICY project_links_public_select
  ON public.project_links FOR SELECT TO anon
  USING (
    EXISTS (
      SELECT 1 FROM public.projects AS p
      WHERE p.project_id = project_links.project_id
        AND p.is_published = true
    )
  );

COMMIT;
